name: Bump Version and Tag Reusable Workflow

on:
  workflow_call:
    inputs:
      bump_type:
        description: 'Version Bump Type'
        type: choice
        options: ['major', 'minor', 'patch', 'none']
        required: false
        default: 'none'
      dry_run:
        description: 'Dry Run'
        type: boolean
        required: false
        default: false
    secrets:
      GITHUB_TOKEN:
        description: 'Token for AllenInstitute GitHub'
        required: true
      GIT_SSH_PRIVATE_KEY:
        description: 'SSH private key for AllenInstitute GitHub'
        required: true
    outputs:
      new_tag:
        description: 'The new tag created'
        value: ${{ jobs.tag.outputs.new_tag }}
      tag:
        description: 'The tag'
        value: ${{ jobs.tag.outputs.tag }}
      part:
        description: 'The part of the version that was bumped'
        value: ${{ jobs.tag.outputs.part }}

jobs:
  tag:
    name: Get New Tag
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bump-version-tag.outputs.new_tag }}
      tag: ${{ steps.bump-version-tag.outputs.tag }}
      part: ${{ steps.bump-version-tag.outputs.part }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump patch version and tag
        id: bump-version-tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ inputs.bump_type }}
          WITH_V: "true"
          RELEASE_BRANCHES: main
          # We don't want to actually push the tag, just get the new tag here. 
          # We'll push the tag in the next step.
          DRY_RUN: true
  update-version-and-tag:
    name: Update Repo Tag and Version
    runs-on: ubuntu-latest
    needs: tag
    if: needs.tag.outputs.part != 'none'
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git User
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Configure AllenInstitute Repo Authorization
        uses: ./.github/actions/setup-ai-github-urls
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
      - name: Update Version
        env:
          VERSION_TAG: ${{ needs.tag.outputs.tag }}
        run: |
          echo "Updating version to ${{ env.VERSION_TAG }}"
          new_version=$(echo $VERSION_TAG | sed 's/^v//')
          echo "Release version: $new_version"
          find src -name '_version.py' -exec sed -i "s/__version__ = .*/__version__ = \"$new_version\"/" {} \;
          git add src/**/_version.py
          git commit -m "Bump version to ${{ env.VERSION_TAG }}"
          git tag -a ${{ env.VERSION_TAG }} -m "Release ${{ env.VERSION_TAG }}"
          git push
          git push --tags
