name: Auto Tag

on:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'src/**.py'
  #     - 'test/**.py'
  #     - 'Makefile'
  #     - 'pyproject.toml'
  #   paths-ignore:
  #     - '**/__version__.py'

  workflow_dispatch:
    inputs:
      bump_type:
        description: 'version bump type'
        type: choice
        options: ['major', 'minor', 'patch', 'none']
        required: false
        default: 'patch'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4        
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Set up AllenInstitute Repo Authorization
        uses: ./.github/actions/setup-ai-github-urls
        with:
          token: ${{ secrets.AI_PACKAGES_TOKEN }}
          ssh_private_key: ${{ secrets.AIBSGITHUB_PRIVATE_KEY }}
      - name: Run Packaging
        run: |
          make release
        shell: bash
  tag:
    name: Tag and Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Bump patch version and tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ github.event.inputs.bump_type || 'patch' }}
          WITH_V: "true"
          RELEASE_BRANCHES: main
          DRY_RUN: true

  
    
    