name: Release

on:
  # push:
  #   tags:
  #     - 'v*'
      
  workflow_dispatch:
    inputs:
      tag:
        description: 'Target Tag for Release'
        type: string
        required: true
      force:
        description: 'Force Release?'
        type: boolean
        required: false
        default: false

jobs:
  package:
      name: Package and Release
      runs-on: ubuntu-latest
      timeout-minutes: 5
      strategy:
        fail-fast: true
        matrix:
          python-version: ["3.9", "3.10", "3.11"]
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4        
          with:
            python-version: ${{ matrix.python-version }}
            cache: 'pip'
        - name: Set up AllenInstitute Repo Authorization
          uses: ./.github/actions/setup-ai-github-urls
          with:
            token: ${{ secrets.AI_PACKAGES_TOKEN }}
            ssh_private_key: ${{ secrets.AIBSGITHUB_PRIVATE_KEY }}
        - name: Run Packaging
          run: |
            make package
          shell: bash
